package com.genesyx.app.domain.content

/**
 * Accessible text of iOS `FreeGuideContent` (the 7-Day Fertility Nutrition Starter Guide).
 * The iOS PDF is 6.3 MB and is not accessibility-tagged; this is the version VoiceOver reads.
 */
sealed interface FreeGuideBlock {
    data class Paragraph(val text: String) : FreeGuideBlock
    data class Subheading(val text: String) : FreeGuideBlock
    data class Bullets(val items: List<String>) : FreeGuideBlock
}

data class FreeGuidePage(val number: Int, val heading: String, val blocks: List<FreeGuideBlock>)

object FreeGuideContent {
    const val title = "7-Day Fertility Nutrition Starter Guide"

    val pages: List<FreeGuidePage> = listOf(
        page(1, "Your 7-Day Fertility Nutrition Starter Guide",
            p("Simple food and lifestyle habits to help you feel more prepared for the pre-conception journey."),
            p("2026"),
        ),
        page(2, "Welcome",
            p("If you're preparing for pregnancy, it can be hard to know where to start. There is so much advice online, and a lot of it feels overwhelming, restrictive, or unrealistic. This guide is here to make things simpler."),
            p("Inside, you'll find a gentle introduction to fertility-friendly nutrition, along with a practical 7-day plan to help you take a few positive first steps."),
            p("This is not about being perfect. It is about building supportive habits, eating well most of the time, and feeling a little more prepared."),
            p("Over the next few pages, we'll focus on simple things that can help:"),
            b("Eating regularly.", "Building balanced meals.", "Including more nutrient-rich foods.", "Supporting steady energy.", "Making small habits feel realistic."),
            p("Think of this as a starting point — a calm, supportive guide to help you begin."),
        ),
        page(3, "A gentle note before you begin",
            p("This guide is for general information only and should not replace personalised advice from your doctor, midwife, fertility team, or dietitian."),
            p("Fertility is influenced by many factors, and no diet or lifestyle approach can guarantee pregnancy."),
            p("Instead, think of this as a helpful starting point — a simple way to begin building supportive habits before pregnancy."),
            p("If you have a medical condition, irregular periods, or you are already under fertility care, it is always best to seek personalised advice alongside any changes you make."),
        ),
        page(4, "Why nutrition matters before pregnancy",
            p("Food is not the only part of the picture, but it can be a helpful place to begin."),
            p("Eating well before pregnancy can support your overall health, energy levels, and nutritional intake, while helping you build a stronger foundation for the months ahead."),
            p("Rather than focusing on one “perfect” food, it is more helpful to think about your overall pattern of eating."),
            p("A simple, balanced approach often works best. That might include:"),
            b("Regular meals.", "Plenty of fruit and vegetables.", "Protein with meals.", "Higher-fibre carbohydrates.", "Healthy fats.", "Enough water.", "Fewer highly processed foods as everyday staples."),
            p("Small, consistent steps really do add up."),
        ),
        page(5, "Hormones and fertility: keeping things steady",
            p("Hormones play an important role in the menstrual cycle, ovulation, and overall reproductive health."),
            p("While food is only one part of the picture, everyday habits such as eating regularly, including enough protein, choosing higher-fibre foods, and getting enough sleep can help support a steadier routine overall."),
            p("This is one reason balanced meals can be so helpful. They may help support more even energy levels and make it easier to stay consistent with your habits."),
            p("Stress, poor sleep, constant energy dips, and an all-or-nothing approach to eating can all make things feel harder than they need to be."),
            p("You do not need to eat perfectly to support your body well. Small, regular habits can make a meaningful difference over time."),
        ),
        page(6, "Gut health: a simple part of the bigger picture",
            p("Gut health has become a popular topic, and while it is not something to overcomplicate, it can be a helpful part of overall wellbeing."),
            p("A balanced diet that includes plenty of fibre-rich plant foods can support digestion and general health. Foods like fruit, vegetables, oats, beans, lentils, nuts, seeds, and live yoghurt can all be useful additions to a balanced routine."),
            p("Rather than focusing on specific “gut health” rules, it is often most helpful to keep things simple:"),
            b("Eat a variety of plant foods.", "Drink enough water.", "Include fibre regularly.", "Limit overly processed foods where you can."),
            p("Again, this is not about perfection. It is about building supportive habits that work in real life."),
        ),
        page(7, "Simple food principles",
            p("You do not need a strict plan to make a positive start."),
            p("A good place to begin is by focusing on a few simple habits:"),
            h("Eat regularly"),
            p("Going long periods without eating can leave you tired, overly hungry, and more likely to grab whatever feels quickest later on."),
            h("Build balanced meals"),
            p("Try to include a source of protein, some fibre, some colour, and healthy fats where you can."),
            h("Think about variety"),
            p("Different foods bring different nutrients, so variety across the week matters more than getting every meal “perfect.”"),
            h("Keep it realistic"),
            p("Simple meals you can repeat are often more helpful than complicated plans you won't stick to."),
            h("Aim for progress, not perfection"),
            p("You do not need to overhaul everything at once. A few small changes done consistently can be a very good place to start."),
        ),
        page(8, "Foods to enjoy more often",
            p("When you're trying to build a supportive pre-conception routine, it can help to include more of the following foods across the week:"),
            h("Colourful fruit and vegetables"),
            p("Think berries, leafy greens, tomatoes, peppers, carrots, broccoli, citrus fruit, and avocado."),
            h("Protein foods"),
            p("Eggs, yoghurt, beans, lentils, tofu, fish, chicken, cottage cheese, and other simple protein options can help meals feel more balanced."),
            h("Higher-fibre carbohydrates"),
            p("Oats, wholegrains, brown rice, quinoa, sweet potatoes, beans, and lentils can support steadier energy."),
            h("Healthy fats"),
            p("Olive oil, nuts, seeds, avocado, and oily fish can all be part of a balanced routine."),
            h("Simple gut-friendly foods"),
            p("Fibre-rich foods and foods like live yoghurt or kefir can be a helpful addition for some people as part of an overall balanced diet."),
            p("You do not need to eat all of these every day. The aim is simply to bring them in more often over time."),
        ),
        page(9, "Foods and habits to be mindful of",
            p("A balanced approach also means being a little more aware of things that can crowd out nourishing choices."),
            p("Try to be mindful of:"),
            b("Frequent sugary snacks and drinks.", "Relying heavily on ultra-processed foods.", "Skipping meals and then overeating later.", "Too much caffeine.", "Regular alcohol.", "Eating in a rushed, distracted way all the time."),
            p("This is not about cutting everything out."),
            p("It is about making supportive choices more often, and noticing the habits that make you feel your best."),
        ),
        page(10, "Your 7-day starter plan",
            p("This week is not about following a perfect menu."),
            p("It is about building a few simple habits that can help you feel more prepared, more nourished, and more in control."),
            p("Each day focuses on one small area to work on. Take what feels helpful, move at your own pace, and remember that consistency matters more than perfection."),
        ),
        page(11, "Day 1: Start with regular meals",
            h("Today's focus"), p("Try not to leave long gaps between meals."),
            h("Why it matters"), p("When you skip meals or go too long without eating, energy can dip and it can become harder to make balanced choices later in the day. For many people, a more regular eating pattern feels steadier and easier to maintain."),
            h("What this can look like"), p("This does not mean eating on a rigid schedule. It simply means aiming for a gentle rhythm across the day. For example:"),
            b("Breakfast in the morning.", "Lunch around the middle of the day.", "Dinner in the evening.", "A snack if needed between meals."),
            h("Easy ways to do it"),
            b("Eat something within a couple of hours after getting up.", "Avoid relying on coffee until lunch time.", "Keep a simple snack ready for busy days.", "Try not to skip lunch and then overeat later on."),
            h("Try this today"), p("Plan roughly when you will eat your three main meals today."),
            h("Reflection"), p("Did eating more regularly help you feel calmer or more energised?"),
        ),
        page(12, "Day 2: Build meals around balance",
            h("Today's focus"), p("Aim to make meals a little more balanced."),
            h("Why it matters"), p("A balanced meal can help you feel fuller for longer and support steadier energy through the day."),
            h("What this can look like"), p("Try building meals around:"),
            b("A protein food.", "A higher-fibre carbohydrate.", "Some colour from fruit or vegetables.", "A healthy fat."),
            h("Easy ways to do it"),
            b("Porridge with yoghurt, berries, and seeds.", "Eggs on wholegrain toast with avocado.", "Lentil soup with wholegrain bread.", "Salmon, rice, and vegetables.", "A jacket potato with beans and salad."),
            h("Try this today"), p("Choose one meal today and ask yourself: could I add protein, fibre, colour, or healthy fat here?"),
            h("Reflection"), p("What meal felt easiest to improve?"),
        ),
        page(13, "Day 3: Add more colour",
            h("Today's focus"), p("Include more fruit and vegetables across the day."),
            h("Why it matters"), p("Fruit and vegetables help add fibre, vitamins, minerals, and variety."),
            h("Easy ways to do it"),
            b("Berries with breakfast.", "Salad in a sandwich or wrap.", "Chopped veg with lunch.", "Extra vegetables with dinner.", "Fruit as part of a snack.", "Frozen vegetables for convenience."),
            h("Try this today"), p("Add one extra fruit or vegetable portion to two meals."),
            h("Reflection"), p("What meal felt easiest to add? Fruit, salad, cooked vegetables, or something else?"),
        ),
        page(14, "Day 4: Focus on protein",
            h("Today's focus"), p("Include a source of protein at meals, and sometimes snacks too."),
            h("Why it matters"), p("Protein can help meals feel more satisfying and can support a steadier eating pattern through the day."),
            h("What this can look like"), p("Protein foods include:"),
            b("Eggs", "Yoghurt", "Beans", "Lentils", "Tofu", "Chicken", "Fish", "Cheese", "Cottage cheese", "Nuts", "Seeds"),
            h("Easy ways to do it"),
            b("Add Greek yoghurt to breakfast.", "Choose eggs on toast instead of toast alone.", "Include beans or lentils in soups and salads.", "Build lunches around chicken, tuna, tofu, or chickpeas.", "Choose yoghurt, nuts, or boiled eggs as a snack."),
            h("Try this today"), p("Look at your breakfast and lunch and see where you could make protein a little more obvious."),
            h("Reflection"), p("Which protein options feel easiest for your routine?"),
        ),
        page(15, "Day 5: Think about fibre and healthy fats",
            h("Today's focus"), p("Bring in foods that help meals feel more nourishing and satisfying."),
            h("Why it matters"), p("Fibre and healthy fats can help support a balanced way of eating and make meals feel more complete."),
            h("What this can look like"), p("Foods to think about more often include:"),
            b("Oats", "Beans", "Lentils", "Wholegrains", "Vegetables", "Fruit", "Avocado", "Olive oil", "Nuts", "Seeds"),
            h("Easy ways to do it"),
            b("Drizzle olive oil on salads or vegetables.", "Add seeds to yoghurt or porridge.", "Include avocado with lunch.", "Swap to wholegrain bread or oats.", "Add beans or lentils to meals you already make."),
            h("Try this today"), p("Choose one meal and one snack where you can add either fibre or healthy fats."),
            h("Reflection"), p("What small swap felt most realistic?"),
        ),
        page(16, "Day 6: Support the basics",
            h("Today's focus"), p("Pay attention to the basics that often get overlooked."),
            h("Why it matters"), p("Food matters, but so do the habits around it. Hydration, sleep, stress, and a little movement can all help you feel more supported and more consistent."),
            h("What this can look like"), p("Keep it simple:"),
            b("Drink water regularly.", "Go for a short walk.", "Eat sitting down where you can.", "Slow things down slightly.", "Aim for a better bedtime tonight."),
            h("Easy ways to do it"),
            b("Keep a water bottle nearby.", "Take a 10-minute walk after lunch.", "Put your phone down while eating one meal.", "Prep breakfast or lunch for tomorrow.", "Go to bed a little earlier than usual."),
            h("Try this today"), p("Pick one non-food habit to support yourself with."),
            h("Reflection"), p("What basic habit makes the biggest difference to how you feel?"),
        ),
        page(17, "Day 7: Make it realistic",
            h("Today's focus"), p("Work out what feels sustainable for you."),
            h("Why it matters"), p("The best routine is not the most perfect one — it is the one you can keep going with."),
            h("What this can look like"),
            b("What felt easy.", "What felt difficult.", "What meals or habits you would repeat.", "What support would help next."),
            h("Easy ways to do it"), p("Write down:"),
            b("3 breakfasts you would happily repeat.", "3 lunches or dinners that feel easy.", "3 snacks that work for busy days.", "2 habits you want to continue next week."),
            h("Try this today"), p("Create your own “keep it going” list for next week."),
            h("Reflection"), p("What are the two or three changes you genuinely want to keep?"),
        ),
        page(18, "A simple starter shopping list",
            p("You do not need a long or expensive list to get started."),
            p("A few useful staples might include:"),
            h("Fruit and vegetables"),
            b("Berries", "Bananas", "Apples", "Leafy greens", "Tomatoes", "Cucumbers", "Peppers", "Carrots", "Broccoli", "Sweet potatoes", "Avocados"),
            h("Protein foods"),
            b("Eggs", "Greek yoghurt", "Cottage cheese", "Chicken", "Fish", "Tofu", "Beans", "Lentils", "Chickpeas"),
            h("Carbohydrates and fibre-rich foods"),
            b("Oats", "Brown rice", "Quinoa", "Wholegrain bread", "Potatoes", "Wraps", "Lentils", "Beans"),
            h("Healthy fats and extras"),
            b("Olive oil", "Nuts", "Seeds", "Hummus", "Nut butter"),
            p("Choose what suits your taste, budget, and routine."),
        ),
        page(19, "A gentle note for partners",
            p("Preparing for pregnancy can be a shared journey."),
            p("While this guide is focused mainly on general nutrition habits before pregnancy, it is worth remembering that overall health matters for partners too."),
            p("Simple habits such as:"),
            b("Eating well.", "Sleeping enough.", "Staying active.", "Reducing smoking.", "Cutting back on excess alcohol.", "Managing stress where possible."),
            p("Can all be supportive steps as part of a wider healthy lifestyle."),
            p("You do not need to do everything at once. Small changes count here too."),
        ),
        page(20, "You've made a start",
            p("And that matters more than you think."),
            p("Trying to conceive can bring a mix of hope, excitement, questions, and uncertainty. But building a few supportive habits can help you feel more grounded and more in control."),
            p("Thank you for reading this guide."),
            p("We hope it has given you a calm and practical place to begin."),
            p("Everything here carries on inside Genesyx. Track how you feel, log what you eat and drink, and read a little more each week."),
        ),
    )

    private fun page(n: Int, heading: String, vararg blocks: FreeGuideBlock) =
        FreeGuidePage(n, heading, blocks.toList())
    private fun p(text: String) = FreeGuideBlock.Paragraph(text)
    private fun h(text: String) = FreeGuideBlock.Subheading(text)
    private fun b(vararg items: String) = FreeGuideBlock.Bullets(items.toList())
}
